export const CHANGE_INPUT_VALUE = "CHANGE_INPUT_VALUE";
export const CHANGE_INPUT_TYPE = "CHANGE_INPUT_TYPE";
export const CHANGE_OUTPUT_VALUE = "CHANGE_OUTPUT_VALUE";
export const CHANGE_OUTPUT_TYPE = "CHANGE_OUTPUT_TYPE";